using IonFiltra.BagFilters.Application.DTOs.Bagfilters.BagfilterInputs;
using IonFiltra.BagFilters.Core.Entities.Bagfilters.BagfilterInputs;

namespace IonFiltra.BagFilters.Application.Mappers.Bagfilters.BagfilterInputs
{
    public static class BagfilterInputMapper
    {
        public static BagfilterInputMainDto ToMainDto(BagfilterInput entity)
        {
            if (entity == null) return null;
            return new BagfilterInputMainDto
            {
                BagfilterInputId = entity.BagfilterInputId,
                BagfilterMasterId = entity.BagfilterMasterId,
                BagFilterName = entity.BagfilterMaster?.BagFilterName,
                BagfilterInput = new BagfilterInputDto
                {
                    EnquiryId = entity.EnquiryId,
                    Process_Volume_M3h = entity.Process_Volume_M3h,
                    Design_Pressure_Mmwc = entity.Design_Pressure_Mmwc,
                    Mfg_Plant = entity.Mfg_Plant,
                    Destination_State = entity.Destination_State,
                    Location = entity.Location,
                    Process_Dust = entity.Process_Dust,
                    Process_Dustload_Gmspm3 = entity.Process_Dustload_Gmspm3,
                    Process_Temp_C = entity.Process_Temp_C,
                    Dew_Point_C = entity.Dew_Point_C,
                    Outlet_Emission_Mgpm3 = entity.Outlet_Emission_Mgpm3,
                    Process_Cloth_Ratio = entity.Process_Cloth_Ratio,
                    Can_Correction = entity.Can_Correction,
                    Customer_Equipment_Tag_No = entity.Customer_Equipment_Tag_No,
                    Bagfilter_Cleaning_Type = entity.Bagfilter_Cleaning_Type,
                    Offline_Maintainence = entity.Offline_Maintainence,
                    Cage_Type = entity.Cage_Type,
                    Cage_Sub_Type = entity.Cage_Sub_Type,
                    Cage_Material = entity.Cage_Material,
                    Cage_Wire_Dia = entity.Cage_Wire_Dia,
                    No_Of_Cage_Wires = entity.No_Of_Cage_Wires,
                    Ring_Spacing = entity.Ring_Spacing,
                    Cage_Diameter = entity.Cage_Diameter,
                    Cage_Length = entity.Cage_Length,
                    Spare_Cages = entity.Spare_Cages,
                    Cage_Configuration = entity.Cage_Configuration,
                    Filter_Bag_Dia = entity.Filter_Bag_Dia,
                    Fil_Bag_Length = entity.Fil_Bag_Length,
                    Fil_Bag_Recommendation = entity.Fil_Bag_Recommendation,
                    Gas_Entry = entity.Gas_Entry,
                    Support_Structure_Type = entity.Support_Structure_Type,
                   
                    Valve_Size = entity.Valve_Size,
                    Voltage_Rating = entity.Voltage_Rating,
                    Capsule_Height = entity.Capsule_Height,
                    Total_Capsule_Height = entity.Total_Capsule_Height,
                    Tube_Sheet_Thickness = entity.Tube_Sheet_Thickness,
                    Capsule_Wall_Thickness = entity.Capsule_Wall_Thickness,
                    Canopy = entity.Canopy,
                    Solenoid_Valve_Maintainence = entity.Solenoid_Valve_Maintainence,
                    Casing_Wall_Thickness = entity.Casing_Wall_Thickness,
                    Stiffening_Factor_Casing = entity.Stiffening_Factor_Casing,
                    Hopper_Type = entity.Hopper_Type,
                    Process_Compartments = entity.Process_Compartments,
                    Tot_No_Of_Hoppers = entity.Tot_No_Of_Hoppers,
                    Tot_No_Of_Trough = entity.Tot_No_Of_Trough,
                    Plenum_Width = entity.Plenum_Width,
                    Inlet_Height = entity.Inlet_Height,
                    Hopper_Thickness = entity.Hopper_Thickness,
                    Hopper_Valley_Angle = entity.Hopper_Valley_Angle,
                    Access_Door_Type = entity.Access_Door_Type,
                    Access_Door_Qty = entity.Access_Door_Qty,
                    Rav_Maintainence_Pltform = entity.Rav_Maintainence_Pltform,
                    Hopper_Access_Stool = entity.Hopper_Access_Stool,
                    Is_Distance_Piece = entity.Is_Distance_Piece,
                    Distance_Piece_Height = entity.Distance_Piece_Height,
                    Stiffening_Factor_Hopper = entity.Stiffening_Factor_Hopper,
                    Hopper = entity.Hopper,
                    Discharge_Opening_Sqr = entity.Discharge_Opening_Sqr,
                    Rav_Height = entity.Rav_Height, //new
                    Material_Handling = entity.Material_Handling,
                    Material_Handling_Qty = entity.Material_Handling_Qty,
                    Trough_Outlet_Length = entity.Trough_Outlet_Length,
                    Trough_Outlet_Width = entity.Trough_Outlet_Width,
                    Material_Handling_XXX = entity.Material_Handling_XXX,
                    Support_Struct_Type = entity.Support_Struct_Type,
                    No_Of_Column = entity.No_Of_Column,
                    Ground_Clearance = entity.Ground_Clearance,
                    Slide_Gate_Height = entity.Slide_Gate_Height, //new
                    Access_Type = entity.Access_Type,
                    Cage_Weight_Ladder = entity.Cage_Weight_Ladder,
                    Mid_Landing_Pltform = entity.Mid_Landing_Pltform,
                    Platform_Weight = entity.Platform_Weight,
                    Staircase_Height = entity.Staircase_Height,
                    Staircase_Weight = entity.Staircase_Weight,
                    Railing_Weight = entity.Railing_Weight,
                    Maintainence_Pltform = entity.Maintainence_Pltform,
                    //Maintainence_Pltform_Weight = entity.Maintainence_Pltform_Weight,
                    Blow_Pipe = entity.Blow_Pipe,
                    Pressure_Header = entity.Pressure_Header,
                    Distance_Piece = entity.Distance_Piece,
                    Access_Stool_Size_Mm = entity.Access_Stool_Size_Mm,
                    Access_Stool_Size_Kg = entity.Access_Stool_Size_Kg,
                    Roof_Door_Thickness = entity.Roof_Door_Thickness,
                    Stiffening_Factor_Roof_Door = entity.Stiffening_Factor_Roof_Door,
                    Column_Height = entity.Column_Height,
                    Bag_Per_Row = entity.Bag_Per_Row, //calculated
                    Number_Of_Rows = entity.Number_Of_Rows, //calculated
                    Is_Damper_Required = entity.Is_Damper_Required,
                    Damper_Series = entity.Damper_Series,
                    Damper_Diameter = entity.Damper_Diameter,
                    Damper_Qty = entity.Damper_Qty,
                    Column_Section = entity.Column_Section,
                    Beam_Tie_Section = entity.Beam_Tie_Section,
                    Rav_Section = entity.Rav_Section,
                    Bracing_Section = entity.Bracing_Section,
                    //S3dModel = entity.S3dModel,
                },

            };
        }

        public static BagfilterInput ToEntity(BagfilterInputMainDto dto)
        {
            if (dto == null) return null;
            return new BagfilterInput
            {
                BagfilterInputId = dto.BagfilterInputId,
                BagfilterMasterId = dto.BagfilterMasterId,
                EnquiryId = dto.BagfilterInput.EnquiryId,
                Process_Volume_M3h = dto.BagfilterInput.Process_Volume_M3h,
                Design_Pressure_Mmwc = dto.BagfilterInput.Design_Pressure_Mmwc,
                Mfg_Plant = dto.BagfilterInput.Mfg_Plant,
                Destination_State = dto.BagfilterInput.Destination_State,
                Location = dto.BagfilterInput.Location,
                Process_Dust = dto.BagfilterInput.Process_Dust,
                Process_Dustload_Gmspm3 = dto.BagfilterInput.Process_Dustload_Gmspm3,
                Process_Temp_C = dto.BagfilterInput.Process_Temp_C,
                Dew_Point_C = dto.BagfilterInput.Dew_Point_C,
                Outlet_Emission_Mgpm3 = dto.BagfilterInput.Outlet_Emission_Mgpm3,
                Process_Cloth_Ratio = dto.BagfilterInput.Process_Cloth_Ratio,
                Can_Correction = dto.BagfilterInput.Can_Correction,
                Customer_Equipment_Tag_No = dto.BagfilterInput.Customer_Equipment_Tag_No,
                Bagfilter_Cleaning_Type = dto.BagfilterInput.Bagfilter_Cleaning_Type,
                Offline_Maintainence = dto.BagfilterInput.Offline_Maintainence,
                Cage_Type = dto.BagfilterInput.Cage_Type,
                Cage_Sub_Type = dto.BagfilterInput.Cage_Sub_Type,
                Cage_Material = dto.BagfilterInput.Cage_Material,
                Cage_Wire_Dia = dto.BagfilterInput.Cage_Wire_Dia,
                No_Of_Cage_Wires = dto.BagfilterInput.No_Of_Cage_Wires,
                Ring_Spacing = dto.BagfilterInput.Ring_Spacing,
                Cage_Diameter = dto.BagfilterInput.Cage_Diameter,
                Cage_Length = dto.BagfilterInput.Cage_Length,
                Spare_Cages = dto.BagfilterInput.Spare_Cages,
                Cage_Configuration = dto.BagfilterInput.Cage_Configuration,
                Filter_Bag_Dia = dto.BagfilterInput.Filter_Bag_Dia,
                Fil_Bag_Length = dto.BagfilterInput.Fil_Bag_Length,
                Fil_Bag_Recommendation = dto.BagfilterInput.Fil_Bag_Recommendation,
                Gas_Entry = dto.BagfilterInput.Gas_Entry,
                Support_Structure_Type = dto.BagfilterInput.Support_Structure_Type,
                
                Valve_Size = dto.BagfilterInput.Valve_Size,
                Voltage_Rating = dto.BagfilterInput.Voltage_Rating,
                Capsule_Height = dto.BagfilterInput.Capsule_Height,
                Total_Capsule_Height = dto.BagfilterInput.Total_Capsule_Height,
                Tube_Sheet_Thickness = dto.BagfilterInput.Tube_Sheet_Thickness,
                Capsule_Wall_Thickness = dto.BagfilterInput.Capsule_Wall_Thickness,
                Canopy = dto.BagfilterInput.Canopy,
                Solenoid_Valve_Maintainence = dto.BagfilterInput.Solenoid_Valve_Maintainence,
                Casing_Wall_Thickness = dto.BagfilterInput.Casing_Wall_Thickness,
                Stiffening_Factor_Casing = dto.BagfilterInput.Stiffening_Factor_Casing,
                Hopper_Type = dto.BagfilterInput.Hopper_Type,
                Process_Compartments = dto.BagfilterInput.Process_Compartments,
                Tot_No_Of_Hoppers = dto.BagfilterInput.Tot_No_Of_Hoppers,
                Tot_No_Of_Trough = dto.BagfilterInput.Tot_No_Of_Trough,
                Plenum_Width = dto.BagfilterInput.Plenum_Width,
                Inlet_Height = dto.BagfilterInput.Inlet_Height,
                Hopper_Thickness = dto.BagfilterInput.Hopper_Thickness,
                Hopper_Valley_Angle = dto.BagfilterInput.Hopper_Valley_Angle,
                Access_Door_Type = dto.BagfilterInput.Access_Door_Type,
                Access_Door_Qty = dto.BagfilterInput.Access_Door_Qty,
                Rav_Maintainence_Pltform = dto.BagfilterInput.Rav_Maintainence_Pltform,
                Hopper_Access_Stool = dto.BagfilterInput.Hopper_Access_Stool,
                Is_Distance_Piece = dto.BagfilterInput.Is_Distance_Piece,
                Distance_Piece_Height = dto.BagfilterInput.Distance_Piece_Height,
                Stiffening_Factor_Hopper = dto.BagfilterInput.Stiffening_Factor_Hopper,
                Hopper = dto.BagfilterInput.Hopper,
                Discharge_Opening_Sqr = dto.BagfilterInput.Discharge_Opening_Sqr,
                Rav_Height = dto.BagfilterInput.Rav_Height,
                Material_Handling = dto.BagfilterInput.Material_Handling,
                Material_Handling_Qty = dto.BagfilterInput.Material_Handling_Qty,
                Trough_Outlet_Length = dto.BagfilterInput.Trough_Outlet_Length,
                Trough_Outlet_Width = dto.BagfilterInput.Trough_Outlet_Width,
                Material_Handling_XXX = dto.BagfilterInput.Material_Handling_XXX,
                Support_Struct_Type = dto.BagfilterInput.Support_Struct_Type,
                No_Of_Column = dto.BagfilterInput.No_Of_Column,
                Ground_Clearance = dto.BagfilterInput.Ground_Clearance,
                Slide_Gate_Height = dto.BagfilterInput.Slide_Gate_Height, //new
                Access_Type = dto.BagfilterInput.Access_Type,
                Cage_Weight_Ladder = dto.BagfilterInput.Cage_Weight_Ladder,
                Mid_Landing_Pltform = dto.BagfilterInput.Mid_Landing_Pltform,
                Platform_Weight = dto.BagfilterInput.Platform_Weight,
                Staircase_Height = dto.BagfilterInput.Staircase_Height,
                Staircase_Weight = dto.BagfilterInput.Staircase_Weight,
                Railing_Weight = dto.BagfilterInput.Railing_Weight,
                Maintainence_Pltform = dto.BagfilterInput.Maintainence_Pltform,
                //Maintainence_Pltform_Weight = dto.BagfilterInput.Maintainence_Pltform_Weight,
                Blow_Pipe = dto.BagfilterInput.Blow_Pipe,
                Pressure_Header = dto.BagfilterInput.Pressure_Header,
                Distance_Piece = dto.BagfilterInput.Distance_Piece,
                Access_Stool_Size_Mm = dto.BagfilterInput.Access_Stool_Size_Mm,
                Access_Stool_Size_Kg = dto.BagfilterInput.Access_Stool_Size_Kg,
                Roof_Door_Thickness = dto.BagfilterInput.Roof_Door_Thickness,
                Stiffening_Factor_Roof_Door = dto.BagfilterInput.Stiffening_Factor_Roof_Door,
                Column_Height = dto.BagfilterInput.Column_Height,
                Bag_Per_Row = dto.BagfilterInput.Bag_Per_Row, //calculated
                Number_Of_Rows = dto.BagfilterInput.Number_Of_Rows, //calculated
                Is_Damper_Required = dto.BagfilterInput.Is_Damper_Required,
                Damper_Series = dto.BagfilterInput.Damper_Series,
                Damper_Diameter = dto.BagfilterInput.Damper_Diameter,
                Damper_Qty = dto.BagfilterInput.Damper_Qty,
                Column_Section = dto.BagfilterInput.Column_Section,
                Beam_Tie_Section = dto.BagfilterInput.Beam_Tie_Section,
                Rav_Section = dto.BagfilterInput.Rav_Section,
                Bracing_Section = dto.BagfilterInput.Bracing_Section,
                S3dModel = dto.BagfilterInput.S3dModel,
            };
        }
    }
}
